/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function  HackerRoom(props) {
  const { nodes, materials } = useGLTF('/models/office20.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[24.4895, 131.1375, -1.486]}
        rotation={[-Math.PI / 2, 0, 0.2361]}
        scale={0.0611}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.0002, 0]}>
            <group position={[0.036, 26.2063, -142.4172]} rotation={[-1.9927, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002_Display_0.geometry}
                material={materials.Display}
                position={[-2.5842, 3.3949, -9.1729]}
                rotation={[0.8313, -0.1049, 2.9049]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002_Material006_0.geometry}
                material={materials['Material.006']}
                position={[-2.5842, 3.3949, -9.1729]}
                rotation={[0.8313, -0.1049, 2.9049]}
                scale={1.1573}
              />
            </group>
            <group position={[0, 24.9878, -147.0405]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_KEY_0.geometry}
                material={materials.material}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_Material006_0.geometry}
                material={materials['Material.006']}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_Material006_0001.geometry}
                material={materials['Material.006']}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_Material006_0002.geometry}
                material={materials['Material.006']}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_Material010_0.geometry}
                material={materials['Material.010']}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005_Material011_0.geometry}
                material={materials['Material.011']}
                position={[-2.5971, -0.7572, -9.7607]}
                rotation={[0, 0, 2.8831]}
                scale={1.1573}
              />
            </group>
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_table_mat_0.geometry}
        material={materials.table_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground_ground_mat_0.geometry}
        material={materials.ground_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.U1602B_U1602B_0.geometry}
        material={materials.U1602B}
        position={[35.2749, 78.5016, -14.1495]}
        rotation={[-3.0158, -0.2164, -Math.PI]}
        scale={3.4457}
      />
      <group position={[52.2085, 72.1675, -26.6698]} scale={110.6884}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001'].geometry}
          material={materials['PlasticoPreto.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_1'].geometry}
          material={materials['Metal.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_2'].geometry}
          material={materials['PCB_topo.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_3'].geometry}
          material={materials['Material.030']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_4'].geometry}
          material={materials['LED.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_5'].geometry}
          material={materials['laranja.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_6'].geometry}
          material={materials['Material.031']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_7'].geometry}
          material={materials['_BRANCO.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_8'].geometry}
          material={materials['Material.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_9'].geometry}
          material={materials['Materiais.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_10'].geometry}
          material={materials['PCB_BASE.001']}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes['20__header_female_6001_11'].geometry}
          material={materials['Protoboard.003']}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_1.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_2.geometry}
          material={materials.plastico_branco}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_3.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_4.geometry}
          material={materials.CINZA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_5.geometry}
          material={materials['pcb verde']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_6.geometry}
          material={materials['Contato PCB']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_7.geometry}
          material={materials.plastico_preto}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_8.geometry}
          material={materials['display_azul.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_9.geometry}
          material={materials['metal_amarelo.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_10.geometry}
          material={materials['metal_parafuso.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_11.geometry}
          material={materials['plastico_preto.015']}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Breadboard_1001.geometry}
          material={materials['Protoboard.001']}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Breadboard_1001_1.geometry}
          material={materials['PlasticoPreto.006']}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Breadboard_1001_2.geometry}
          material={materials['Vermelgo_Fio.001']}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Breadboard_1001_3.geometry}
          material={materials['Azul_Servo.001']}
        /> */}
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Breadboard_1001_4.geometry}
          material={materials['PlasticoPreto.009']}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002'].geometry}
          material={materials['laranja.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002_1'].geometry}
          material={materials['PLACA_AZUL.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002_2'].geometry}
          material={materials['METAL.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002_3'].geometry}
          material={materials['GRADE_PRETA.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002_4'].geometry}
          material={materials['Branco.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Ultrasonic_Sensor_HC-SR04002_5'].geometry}
          material={materials['Material.024']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lamp.geometry}
        material={materials.Lamp}
        position={[-36.5153, 89.7374, 6.6586]}
        rotation={[-1.5731, 0, 0]}
        scale={8.7392}
      />
      <group
        position={[-28.6719, 71.6576, -11.783]}
        rotation={[-Math.PI, 0.3451, -Math.PI]}
        scale={1.3141}>
        <group position={[0.022, 0.8582, 4.959]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper_Paper_0.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paper_PaperSide_0.geometry}
            material={materials.PaperSide}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Binding_Plastic_0.geometry}
          material={materials.Plastic}
          position={[-0.011, 0.5527, -2.4795]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cartonage_Cardboard_0.geometry}
          material={materials.Cardboard}
          position={[0.022, 0.398, 4.959]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        />
      </group>
      <group
        position={[-10.5369, 71.9287, -18.6016]}
        rotation={[0, -0.0851, -Math.PI]}
        scale={77.4767}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.0371, 0.079, 0]} scale={[0.9938, 1.0033, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21001.geometry}
              material={materials['Phone_color.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21001_1.geometry}
              material={materials['Black_Screen.001']}
            />
          </group>
        </group>
      </group>
      {/* <group
        position={[-19.5239, 73.8334, 12.2025]}
        rotation={[0.1514, -1.0454, -Math.PI / 2]}
        scale={0.0313}>
        <group
          position={[41.5359, -16.189, -179.0972]}
          rotation={[-1.5756, 0, -Math.PI]}
          scale={103.4949}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_1.geometry}
            material={materials.Button_top}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_2.geometry}
            material={materials.Headrest}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_3.geometry}
            material={materials.Metallic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_4.geometry}
            material={materials.Speakers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_5.geometry}
            material={materials.Mesh_drill}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Digital_Crown_Button_top_0_6.geometry}
            material={materials.Headset}
          />
        </group>
      </group> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_On_Headset_Button_top_0.geometry}
        material={materials.Button_top}
      />
      <group position={[30.744, 0, -80.644]} rotation={[-Math.PI / 2, 0, 0]} scale={14.7828}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13002.geometry}
          material={materials.Photo}
          position={[1.3509, -6.3462, 5.2724]}
          rotation={[0, 0, 2.3218]}
          scale={1.2765}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Cactus.001']}
          position={[-5.5071, -7.6803, 5.2117]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3002.geometry}
          material={materials['Cactus.001']}
          position={[3.7194, -3.3063, 6.4321]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6001.geometry}
          material={materials['File_Storage.001']}
          position={[3.7666, -2.9421, 3.0534]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/office17.glb')